PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/43ee4ae1844c6fb756f2ad5ac721f770f8fef8f1

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/7fffab1610d2ea08a95383febd0579e0037b6b51) in current PX4/master (5819c82678b1f11f1b0d36180027eb66350ea725)
https://github.com/PX4/NuttX/compare/7fffab1610d2ea08a95383febd0579e0037b6b51...43ee4ae1844c6fb756f2ad5ac721f770f8fef8f1

43ee4ae184 (HEAD, origin/master) wireless: ieee802154: nxstyle fixes
de11caffba wireless: pktradio: nxstyle fixes
e36d93f600 wireless: bluetooth: nxstyle fixes
0a673d759d Corrected build error
e6af32c88f Run nxstyle against all files modified by PR 848
2f7e003ef8 arch/arm/src/armv7-m:  Use Apache 2.0 license
048d4954a0 crypto: nxstyle fixes
e6b47ea948 video: videomode: nxstyle cleanup
7ddf7c6c25 binfmt: nxstyle fixes
02ab0cd149 stm32: Fix typos, wrong comments, and nxstyle.

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/51cbd422271891ae287111b180e33275b109278d

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/95e105548a2037f42bf2f13b214ae083b921ff03) in current PX4/master (5819c82678b1f11f1b0d36180027eb66350ea725)
https://github.com/PX4/NuttX-apps/compare/95e105548a2037f42bf2f13b214ae083b921ff03...51cbd422271891ae287111b180e33275b109278d

51cbd422 (HEAD -> master, origin/master) Revert "build.yml: Remove -G from cibuild.sh command line"
2749e646 system: nxplayer & nxrecorder: nxstyle fixes
1697c649 examples: nxwidget: nxstyle fixes
c9eaf0be examples: i2sloop: nxstyle fixes
3cdb8107 examples: i2schar: nxstyle fixes
989988fa build.yml: Remove -G from cibuild.sh command line
f18b283e nshlib: add printf command to README.TXT
63288eb8 fix apps/include/graphics/nxwidgets/cwidgetcontrol.hxx:550:20: error: ‘m_xyinput’ was not declared in this scope
68ed2a2a build.yaml: Change arm-11 to arm-12
0c84e22a example: Remove all APPNAME from Makefile